# general settings
name: AD_MI2_x4_2022_11_06   
model_type: AD_RealESRGANModel  
scale: 4  #   X4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 10

# ----------------- options for synthesizing training data in RealESRNetModel ----------------- #
gt_usm: True  # USM the ground-truth

# the first degradation process
resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
resize_range: [0.15, 1.5]
gaussian_noise_prob: 0.5
noise_range: [1, 30]
poisson_scale_range: [0.05, 3]
gray_noise_prob: 0.4
jpeg_range: [30, 95]

# the second degradation process
second_blur_prob: 0.8
resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
resize_range2: [0.3, 1.2]
gaussian_noise_prob2: 0.5
noise_range2: [1, 25]
poisson_scale_range2: [0.05, 2.5]
gray_noise_prob2: 0.4
jpeg_range2: [30, 95]

gt_size: 256
queue_size: 180

 
datasets:
  train:
    name: DF2K+OST+DIV8K
    type: AD_RealESRGANDataset  #  数据加载部分
#    dataroot_gt: /home/ps/data/data_1/SR/datasets/PGW_test/PGW_RealSR_train/HR_sub1
#    dataroot_edge: /home/ps/data/data_1/SR/datasets/PGW_test/PGW_RealSR_train/EDGE_sub1
#    meta_info: /home/ps/data/data_1/SR/datasets/PGW_test/PGW_RealSR_train/meta_info_PGW_RealSR1.txt
    dataroot_gt: /home/ps/data/data_1/SR/datasets/PGW_test/DF2K+DIV8K+Outdoor/train_HR_sub
    dataroot_edge: /home/ps/data/data_1/SR/datasets/PGW_test/DF2K+DIV8K+Outdoor/train_EDGE_sub
    meta_info: /home/ps/data/data_1/SR/datasets/PGW_test/DF2K+DIV8K+Outdoor/meta_info_DF2K+DIV8.txt
    io_backend:
      type: disk

    blur_kernel_size: 21
    kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob: 0.1
    blur_sigma: [0.2, 3]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 21
    kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob2: 0.1
    blur_sigma2: [0.2, 1.5]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.8

    gt_size: 256
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 5
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~






  val_1:
    name: RealSR  
    type: PairedImageDataset
    dataroot_gt: /home/ps/data/data_1/SR/datasets/real_world/RealSR_Canon+Nikon/Test/HR4
    dataroot_lq: /home/ps/data/data_1/SR/datasets/real_world/RealSR_Canon+Nikon/Test/x4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk
 

# network structure 
network_g:
  type: AttackDefensev3 
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64  
#  num_block: 4
  upscale: 4
#  res_scale: 1
#  img_range: 255.
#  rgb_mean: [0.4488, 0.4371, 0.4040]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
 
  resume_state: ~   
# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5



  total_iter: 1000000  
  warmup_iter: -1   

 
  pixel_opt1:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
 
  pixel_opt2:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
 
  MI:
    type: MutualInformationLoss
#  pixel_opt3:
#    type: MutualInformationLoss



## validation settings
#val:
#  val_freq: !!float 2e2  # 1000
#  save_img: false

#  metrics:
#    psnr: # metric name, can be arbitrary
#      type: calculate_psnr
#      crop_border: 2
#      test_y_channel: false
  metrics:
    psnr:  
      type: calculate_psnr 
      crop_border: 4 
      test_y_channel: True 
    ssim:
      type: calculate_ssim  
      crop_border: 4  
      test_y_channel: true  
#    niqe:
#      type: calculate_niqe  
#      crop_border: 4  
#      test_y_channel: false  

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 10e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500


 

pid_name: edgeassistv2_x4